# Common config for all CLI tools.
# Copy file to ~/.config/cli-tools.toml

[dirmove]
# auto = false
# debug = false
# dryrun = false
# include = []
# exclude = []
# min_group_size = 3
# overwrite = false
# prefix_overrides = ["longer.prefix", "some.name"]
# recursive = false
# verbose = false

[dots]
# date_starts_with_year = true
# debug = false
# directory = false
# dryrun = false
# increment = false
# include = []
# move_date_after_prefix = []
# move_to_end = []
# move_to_start = []
# overwrite = false
# prefix_dir = false
# suffix_dir = false
# pre_replace = []
# recursive = false
# regex_replace = []
# remove_random = false
# remove_from_start = []
# verbose = false

# replacement pairs:
replace = [
    [".WEBDL", ""],
    [".HEVC", ".x265"],
]

[flip_date]
# directory = false
# dryrun = false
# file_extensions = []
# overwrite = false
# recursive = false
# swap_year = false
# verbose = false
# year_first = false

[video_convert]
# bitrate = 8000
# convert_all_types = false
# convert_other_types = false
# delete = false
# exclude = []
# include = []
# extensions = []
# number = 0
# overwrite = false
# recursive = false
# verbose = false

[dupefind]
# default_paths = []
# dryrun = false
# extensions = ["mp4", "mkv", "avi", "mov", "wmv", "webm"]
# move_files = false
# paths = []
# recurse = false
# verbose = false

# Identifier patterns to search for (regex)
patterns = [
    "GIO\\d{3,4}",
    "SZ\\d{3,4}",
    "NRX\\d{3,4}",
    "VG\\d{3,4}",
    "EKS\\d{3,4}",
]
